apiVersion: apps/v1
kind: Deployment
metadata:
  name: chilisauce-app
  namespace: chilisauce
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 3
  selector:
    matchLabels:
      app: chilisauce-backend
  template:
    metadata:
      labels:
        app: chilisauce-backend
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: fluentbit-config
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:2.2.0
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/app
            - name: config-volume
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
        - name: chilisauce
          image: 0892668/chilisauce-be:0.0.7
          imagePullPolicy: Always
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/app
          env:
            - name: SPRING_DATA_REDIS_HOST
              value: redis-service.default.svc.cluster.local
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "1500m"
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh","-c","sleep 10" ]
          startupProbe:
            httpGet:
              path: /probe/startup
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /probe/ready
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 1
            successThreshold: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /probe/live
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 1
            failureThreshold: 7

