apiVersion: v1
kind: ResourceQuota
metadata:
  name: chilisauce-quota
  namespace: chilisauce
spec:
  hard:
    requests.cpu: "5"
    requests.memory: 10Gi
    limits.cpu: "10"
    limits.memory: 10Gi
    pods: 5
    services: 5