jwt.secret.key: 'ee5038163ddeee3e32ed6f402788ec3a445ddda1878a4b50df85b5d2510a538d8bc58534e15be05d548eaa19621e39d46cb86cae1495bb85f74416cfed316693'
superuser.certification: 'clfflthtm123!'
# 로그 레벨 설정
logging:
  level:
    root: info
    org:
      apache:
        coyote:
          http11: info
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error # 해당 클래스에서 예외가 발생하면 로그를 출력하지 않음
# Multipart 설정
spring:
  servlet:
    multipart:
      max-file-size: 100MB # 요청한 파일 한 개의 크기
      max-request-size: 100MB # 요청한 파일 전체의 크기
  s3:
    bucket: myboardbucket1210
    access-key:
    secret-key:
mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465
AdminMail:
  id: limsanggyu91@gmail.com
  password: ftnvwmhjdwqhxqmd
# AWS 설정
cloud:
  aws:
    region:
      static: ap-northeast-2  # AWS 기본 리전을 설정
    stack:
      auto: false # Spring Cloud를 실행하면, 서버 구성을 자동화하는 CloudFormation이 실행되는데 이를 사용하지 않으므로 false로 설정
#springdoc swagger
springdoc:
  api-docs:
    path: /api-docs # 접속 path 설정
  swagger-ui:
    path: /api/swagger-ui
    display-request-duration: true  # try it out 을 했을 때 request duration 을 추가로 찍어줌
    disable-swagger-default-url: true
    operations-sorter: alpha
  cache:
    disabled: true # swagger cache 설정
---
spring:
  config:
    activate:
      on-profile: "common-local" # local 환경일 때 적용
logging.level:
  org.apache.coyote.http11: info # 콘솔에 http 요청을 로그로 보여줄 수 있는 설정
---
spring:
  config:
    activate:
      on-profile: "common-dev" # dev 환경일 때 적용
logging.level:
  org.apache.coyote.http11: info