spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc.batch_size: 100
        default_fetch_size: 100
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 1000
      javax:
        persistence:
          sharedCache.mode: ALL
---
spring:
  config:
    activate:
      on-profile: "db-local"
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database: H2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;
    username: sa
    password:
#  redis:
#    host: 3.39.23.139
#    port: 6379
#    password: clfflthtm
---
spring:
  config:
    activate:
      on-profile: "db-dev"
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://chillisauce.cpa6sxphwqin.ap-northeast-2.rds.amazonaws.com:3306/Board
    username: admin
    password: clfflthtm
#  redis:
#    host: 3.39.23.139
#    port: 6379
#    password: clfflthtm