server:
  shutdown: graceful

spring:
  profiles:
    active: db-dev
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  datasource:
    url: jdbc:mysql://chillisauce.cpa6sxphwqin.ap-northeast-2.rds.amazonaws.com:3306/Board
    username: admin
    password: clfflthtm
  lifecycle:
    timeout-per-shutdown-phase: 50s
---
mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465
AdminMail:
  id: 0892668@gmail.com
  password: $success089

---
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    disable-swagger-default-url: true
    operations-sorter: alpha
  cache:
    disabled: true
---
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  data:
    redis:
      host: redis-service.default.svc.cluster.local
      port: 6379